apiVersion: fission.io/v1
kind: Function
metadata:
  creationTimestamp: null
  name: ap-aa-change-detection-func
  namespace: fission
spec:
  InvokeStrategy:
    ExecutionStrategy:
      ExecutorType: poolmgr
      MaxScale: 0
      MinScale: 0
      SpecializationTimeout: 120
      TargetCPUPercent: 0
    StrategyType: execution
  concurrency: 500
  configmaps:
  - name: ap-config
    namespace: fission
  environment:
    name: ap-aa-change-detection-func-env
    namespace: fission
  functionTimeout: 900
  idletimeout: 120
  package:
    functionName: change_detection.main
    packageref:
      name: ap-aa-change-detection-func-package
      namespace: fission
  requestsPerPod: 1
  resources: {}
