# IBM Confidential
# PID 5698-OPE
# © Copyright IBM Corp. 2024, 2025

apiVersion: fission.io/v1
kind: MessageQueueTrigger
metadata:
  creationTimestamp: null
  name: ap-aa-change-detection-func-mqt
  namespace: fission
spec:
  contentType: application/json
  cooldownPeriod: 300
  errorTopic: jack_change_detection_err
  functionref:
    functionweights: null
    name: ap-aa-change-detection-func
    type: name
  maxReplicaCount: 1
  maxRetries: 0
  messageQueueType: kafka
  metadata: {}
  minReplicaCount: 0
  mqtkind: fission
  pollingInterval: 30
  respTopic: jack_change_detection_resp
  topic: zou.metrics.00.raw
