include:
- .//ap-aa-change_detection-func-src-pkg.zip
kind: ArchiveUploadSpec
name: ap-aa-change-detection-func-src-pkg-zip-gcKe

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: ap-aa-change-detection-func-package
  namespace: fission
spec:
  buildcmd: ./scripts/build.sh
  deployment:
    checksum: {}
  environment:
    name: ap-aa-change-detection-func-env
    namespace: fission
  source:
    checksum: {}
    type: url
    url: archive://ap-aa-change-detection-func-src-pkg-zip-gcKe
status:
  buildstatus: pending
  lastUpdateTimestamp: "2023-10-13T02:34:27Z"
