version: '3.8'
services:
  python-app:
    image: nab-demo:latest
    command: python /app/utils/lstm_rrcf/flask_server/server_v2/server.py
    # command: python /app/utils/lstm_rrcf/flask_server/watcher.py
    stop_grace_period: 30s
    volumes:
      - ../../utils/lstm_rrcf/flask_server/:/app/utils/lstm_rrcf/flask_server
      - ../../libs:/app/libs
      - ../../projects/nab_detection:/app/projects/nab_detection
    environment:
      - NAB_DETECTION_CONFIG=/app/libs/nab_detection_pkg/aiops_nab_detection/sample-config.yaml
      - AP_ANOMALY_DETECTION_FUNCTION_CONFIG=/app/libs/nab_detection_pkg/aiops_nab_detection/sample-config.yaml
      - ENABLE_RDEBUG=true
      - ENV_NAME=ERIC_LOCAL
      - SAVE_RESULT_LOCAL=true
      - FILE_PATH=/app/projects/nab_detection/nab_detection.py
      - FUNCTION_NAME=main
      - PYTHONPATH=/app/libs/nab_detection_pkg:/app/libs/aiops_unite_pkg
      - FISSION_ENV_CONFIG=/app/utils/lstm_rrcf/flask_server/server_v2/fission_config.yaml
      - LOCAL_RESULT_FILE=/app/libs/fake_data_generator_pkg/fake_data_generator/results.csv
      - LOCAL_RESULT_KAFKA_FILE=/app/libs/fake_data_generator_pkg/fake_data_generator/results_kafka.log
    ports:
      - "8888:8888"
      # - "5678:5678"  # Debugpy port
  redis:
    image: redis:latest
    container_name: redis_dev
    ports:
      - "6379:6379"
    volumes:
      - ./redis_data:/data
    environment:
      - REDIS_APPENDONLY=yes
    restart: unless-stopped
  redis-insight:
    image: redis/redisinsight:latest
    user: "0:0"
    restart: always
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - "5540:5540"
    volumes:
      - /redis-insight:/data