FROM nab-demo:latest
# COPY requirements.txt ./
# RUN apt-get update && \
#     apt-get install -y --no-install-recommends gcc make libc6-dev python3-dev libev-dev && \
#     pip install -r requirements.txt && \
#     apt-get clean
# WORKDIR /app

# Copy files to different folder
COPY utils/lstm_rrcf/flask_server/server_v2 /app/
RUN rm -rf /app/*.pyc || true
RUN mkdir /userfunc
COPY projects/nab_detection /userfunc/
RUN mkdir /userfunc/aiops_nab_detection
COPY libs/nab_detection_pkg/aiops_nab_detection /userfunc/aiops_nab_detection
RUN mkdir /userfunc/aiops_unite
COPY libs/aiops_unite_pkg/aiops_unite /userfunc/aiops_unite
RUN rm -rf /app/*.pyc || true
