include:
- .//ap-aa-training-func-src-pkg.zip
kind: ArchiveUploadSpec
name: ap-aa-training-func-src-pkg-zip-u0vg

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: ap-aa-training-func-package
  namespace: fission
spec:
  buildcmd: ./scripts/build.sh
  deployment:
    checksum: {}
  environment:
    name: ap-aa-training-func-env
    namespace: fission
  source:
    checksum: {}
    type: url
    url: archive://ap-aa-training-func-src-pkg-zip-u0vg
status:
  buildstatus: pending
  lastUpdateTimestamp: "2023-10-05T21:05:34Z"
