[build-system]
requires = ["setuptools>=70.0"]
build-backend = "setuptools.build_meta"

[project]
name = "training_function"
version = "0.1"
authors = [
    {name = "Adarshdeep Cheema", email = "adarshdeep.cheema@ibm.com"},
    {name = "Shreetama Mukherjee", email = "shreetama.mukherjee1@ibm.com"},
    {name = "Jack T. Jia", email = "Jack-Tiefeng.Jia@ibm.com"},
]
description = "training function"
dependencies = [
    "Flask~=3.1"
]

[project.optional-dependencies]
lint = [
    "black~=24.4",
    "flake8~=7.0",
    "flake8-pyproject~=1.2",
    "isort~=5.13",
    "pylint~=3.2",
    "pyright~=1.1"
]

[tool.setuptools]
py-modules = []

[tool.black]
line-length = 120
target-version = ['py38']

[tool.flake8]
max-line-length = 120
# required for compatibility with Black:
extend-ignore = "E203"
exclude = ".env"

[tool.pylint."messages control"]
disable = "all"
enable = [
  "empty-docstring",
  "missing-module-docstring",
  "missing-class-docstring",
  "missing-function-docstring"
]
ignore = ["setup.py", "__init__.py"]
ignore-paths = ['.*/tests', ]

[tool.isort]
profile = "black"
line_length = 120
auto_identify_namespace_packages = false
force_single_line = true # pyright doesn't like implicit namespace + single line (related to https://github.com/microsoft/pyright/issues/2882?)

[tool.pyright]
extraPaths = ["../../libs/training_pkg"]
reportMissingTypeArgument = true  # Report generic classes used without type arguments
strictListInference = true  # Use union types when inferring types of lists elements, instead of Any
